# -*- coding: utf-8 -*-
"""Computer_vision_tf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Uc9J1ZcZGISVBjMWBDXvac_f9psVdUg

# Computer vision Introduction using CNN 
# (Convolutional Neural Network)
* CNN should have non linear activations
* tf.keras.layers.ConvXD where X:
  - 1 = 1D text based
  - 2 = 2D Images
  - 3 = 3D Videos

## Lets now get the data
We will only be using the pizza and steak part of the food101 dataset
"""

import zipfile

# Download zip file of pizza_steak images
!wget https://storage.googleapis.com/ztm_tf_course/food_vision/pizza_steak.zip

# Time to unzip the file
zip_ref = zipfile.ZipFile("pizza_steak.zip","r")
zip_ref.extractall()
zip_ref.close()

# View files
!ls pizza_steak

!ls pizza_steak/train/

