# -*- coding: utf-8 -*-
"""Tensorflow_intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12PhrTIMTMELWoVQI2PxZDTXVgJMLySSi

# Some fundamentals for tensorflow


---
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using `tf.function`
* Using GPUs And TPUs

### Introductions to Tensors
"""

# Imort Tensorflow
import tensorflow as tf


print(tf.__version__)

# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

# View number of tensor dimensions
# `ndim`
scalar.ndim

# Create a vector
vector = tf.constant([10,10])
vector

vector.ndim

# Create a matrix
matrix = tf.constant([[10,10],
                      [8,8]])
matrix

matrix.ndim

# Create a float matrix
another_matrix = tf.constant([[10. , 8,],
                              [5. , 6.],
                              [9. , 7.]],dtype=tf.float16) 
another_matrix

another_matrix.ndim

# Lets now create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,17]]])
tensor

tensor.ndim

"""#### What we have created so far:
* Scalar: A single number
* Vector: A number with directions
* Matrix: A 2-dimensional array of numbers
* Tensor: A n-dimensional array of numbers

### Creating tensors with `tf.Variable`
"""

tf.Variable

# Lets create a changeable tensor

changeable_tensor = tf.Variable([10,10])

unchangeable_tensor = tf.constant([10,10])

changeable_tensor,unchangeable_tensor

# Now lets try changing one of the elements in our changeable tensor

# changeable_tensor[0] = 7 Wont work since is does not support item assignment

changeable_tensor[0].assign(7)
changeable_tensor

"""**Note:** Usually we wont need to decide between `tf.constant` and `tf.Variable` since tensorflow does this on its own.

### Creating Random Tensors
"""

